In [1]:
import pandas as pd 
import numpy as np
import  datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_product=pd.read_csv(r"C:\Users\Asus\Downloads\zoomev\empty\products.csv")
df_sale=pd.read_csv(r'C:\Users\Asus\Downloads\zoomev\empty\sales.csv',parse_dates=['sales_transaction_date'])
df_submail=pd.read_csv(r'C:\Users\Asus\Downloads\zoomev\empty\email_subject.csv')
df_email=pd.read_csv(r'C:\Users\Asus\Downloads\zoomev\emails.csv')
print(df_product)
print('n/')
print(df_sale)

    product_id                   model  year product_type  base_price  \
0            1                  FioNex  2010      scooter       63998   
1            2  FioNex Limited Edition  2011      scooter      127998   
2            3                  FioNex  2013      scooter       79998   
3            4               DeltaPlus  2014   automobile      920000   
4            5                  Parker  2014      scooter      111998   
5            6                  Corpel  2015   automobile      524000   
6            7                  Sprint  2016      scooter       95998   
7            8  Sprint Limited Edition  2017      scooter      111998   
8            9            SigniaSafari  2017   automobile      280000   
9           10               Zelito800  2017   automobile      686000   
10          11               DeltaPlus  2019   automobile      760000   
11          12           FioNex Zester  2019      scooter       55998   

   production_start_date production_end_date  
0  

In [4]:
df_sale['Date']=df_sale['sales_transaction_date'].dt.date

In [7]:
df_sale['Date']=pd.to_datetime(df_sale['Date'])
df_sale.dtypes

customer_id                        int64
product_id                         int64
sales_transaction_date    datetime64[ns]
channel                           object
dealership_id                     object
Date                      datetime64[ns]
dtype: object

In [8]:
df_sprint=df_sale.loc[(df_sale['product_id']==7)&(df_sale['Date']>='2016-10-10')&(df_sale['Date']<='2016-10-30')]

In [9]:
sale_perday=np.array(df_sprint['Date'].value_counts())
sale_perday

array([14, 12, 11, 10, 10, 10, 10,  9,  9,  9,  7,  6,  6,  6,  5,  5,  5,
        5,  4,  2,  2], dtype=int64)

In [10]:
no_of_days=np.arange(1,22,1)
no_of_days

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [12]:
list_of_tuple=list(zip(no_of_days,sale_perday))
df=pd.DataFrame(list_of_tuple,columns=['no_of_days','sale_perday'])
df

no_of_days  sale_perday
0            1           14
1            2           12
2            3           11
3            4           10
4            5           10
5            6           10
6            7           10
7            8            9
8            9            9
9           10            9
10          11            7
11          12            6
12          13            6
13          14            6
14          15            5
15          16            5
16          17            5
17          18            5
18          19            4
19          20            2
20          21            2

In [13]:
x=np.array(df['sale_perday'])
x

array([14, 12, 11, 10, 10, 10, 10,  9,  9,  9,  7,  6,  6,  6,  5,  5,  5,
        5,  4,  2,  2], dtype=int64)

In [14]:
df['sprint_growth']=df['sale_perday'].pct_change(periods=1)*100
df

no_of_days  sale_perday  sprint_growth
0            1           14            NaN
1            2           12     -14.285714
2            3           11      -8.333333
3            4           10      -9.090909
4            5           10       0.000000
5            6           10       0.000000
6            7           10       0.000000
7            8            9     -10.000000
8            9            9       0.000000
9           10            9       0.000000
10          11            7     -22.222222
11          12            6     -14.285714
12          13            6       0.000000
13          14            6       0.000000
14          15            5     -16.666667
15          16            5       0.000000
16          17            5       0.000000
17          18            5       0.000000
18          19            4     -20.000000
19          20            2     -50.000000
20          21            2       0.000000

### Sprint Limited Edition has % growth calculated as -20% on the 16th day after the product launch

In [15]:
df_sle=df_sale.loc[(df_sale['product_id']==8) & (df_sale['Date']>='2017-02-15') & (df_sale['Date']<='2017-03-7')]
df_sle

customer_id  product_id sales_transaction_date     channel  \
7483         46526           8    2017-02-16 03:52:00  dealership   
7490          4323           8    2017-02-25 04:06:00    internet   
7518          6516           8    2017-02-20 22:26:00    internet   
7538         14393           8    2017-03-05 21:53:00  dealership   
7573          4452           8    2017-02-22 14:13:00  dealership   
...            ...         ...                    ...         ...   
12801        42940           8    2017-02-21 10:48:00    internet   
12900        25710           8    2017-03-07 14:48:00    internet   
12921        28499           8    2017-02-28 18:07:00    internet   
13022        30924           8    2017-02-21 21:11:00    internet   
13069        45645           8    2017-02-27 16:34:00    internet   

      dealership_id       Date  
7483              1 2017-02-16  
7490         Online 2017-02-25  
7518         Online 2017-02-20  
7538              5 2017-03-05  
7573              1 2017-02-22  
...             ...        ...  
12801        Online 2017-02-21  
12900        Online 2017-03-07  
12921        Online 2017-02-28  
13022        Online 2017-02-21  
13069        Online 2017-02-27  

[88 rows x 6 columns]

In [16]:
np.array(df_sle['Date'].value_counts())
sale_perdaysle=np.array(df_sle['Date'].value_counts())

In [17]:
no_day=np.arange(1,22,1)
no_day

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [18]:
list_of_tuple=list(zip(no_day,sale_perdaysle))
df_sle=pd.DataFrame(list_of_tuple,columns=['no_day','sale_perdaysle'])
df_sle

no_day  sale_perdaysle
0        1               8
1        2               7
2        3               7
3        4               6
4        5               6
5        6               6
6        7               5
7        8               5
8        9               5
9       10               4
10      11               4
11      12               4
12      13               4
13      14               4
14      15               3
15      16               2
16      17               2
17      18               2
18      19               2
19      20               1
20      21               1

In [19]:
df_sle['Sprint_Limited_Edition_growth']=df_sle['sale_perdaysle'].pct_change(periods=1)*100
df_sle

no_day  sale_perdaysle  Sprint_Limited_Edition_growth
0        1               8                            NaN
1        2               7                     -12.500000
2        3               7                       0.000000
3        4               6                     -14.285714
4        5               6                       0.000000
5        6               6                       0.000000
6        7               5                     -16.666667
7        8               5                       0.000000
8        9               5                       0.000000
9       10               4                     -20.000000
10      11               4                       0.000000
11      12               4                       0.000000
12      13               4                       0.000000
13      14               4                       0.000000
14      15               3                     -25.000000
15      16               2                     -33.333333
16      17               2                       0.000000
17      18               2                       0.000000
18      19               2                       0.000000
19      20               1                     -50.000000
20      21               1                       0.000000